# A conda environment with all useful package for ctapipe developers
name: cta-dev
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - pip
  - astropy=5
  - black
  - bokeh=2
  - nbsphinx >=0.8.12,<0.9
  - cython
  - graphviz
  - h5py
  - iminuit>=2
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib
  - numba=0.56
  - numpy>=1.17
  - numpydoc
  - pandas
  - pre-commit
  - psutil
  - pyirf
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - pytest-astropy-header
  - pyyaml
  - scikit-learn
  - scipy
  - setuptools
  - sphinx=3.5
  - sphinx-automodapi
  - sphinx_rtd_theme
  - tomli
  - towncrier
  - tqdm
  - traitlets
  - vitables
  - wheel
  - xz
  - zlib
  - zstandard
  - eventio>=1.9.1
  - jinja2=3.0 # for sphinx 3.5, remove when updating to 4.x
  - ffmpeg # for making movies in the documentation
