# A conda environment with all useful package for ctapipe developers
name: cta-dev
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11
  - pip
  - astropy=5
  - black
  - bokeh=2
  - nbsphinx
  - cython
  - graphviz
  - h5py
  - iminuit>=2
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib
  - numba>=0.56
  - numpy>=1.22
  - numpydoc
  - pandas
  - pre-commit
  - psutil
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - pytest-astropy-header
  - pyyaml
  - scikit-learn
  - scipy
  - setuptools
  - sphinx
  - sphinx-automodapi
  - pydata-sphinx-theme
  - sphinx-design
  - tomli
  - towncrier
  - tqdm
  - traitlets
  - vitables
  - wheel
  - xz
  - zlib
  - zstandard
  - eventio>=1.9.1
  - ffmpeg # for making movies in the documentation
