name: cta-dev
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - zeromq
  - pyzmq>=17  # needed for correct function of notebooks on OSX
  - astropy
  - bokeh
  - cython
  - gammapy
  - graphviz
  - h5py
  - iminuit
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib
  - numba
  - numpy>=1.15.4
  - numpydoc
  - pandas
  - pyhessio
  - pytest
  - pytest-cov
  - psutil
  - scikit-learn
  - scipy
  - setuptools
  - sphinx=1.7
  - sphinx_rtd_theme
  - sphinx-automodapi
  - traitlets
  - wheel
  - xz
  - pyyaml
  - zlib
  - iminuit
  - pytables
  - tqdm
  - pip:
      - pytest_runner
      - eventio==0.11.0
      - https://github.com/cta-observatory/ctapipe-extra/archive/v0.2.16.tar.gz
