name: cta-dev
channels:
  - anaconda
  - cta-observatory
  - conda-forge
dependencies:
  - zeromq=4.2.2 
  - ctapipe-extra=0.2.*
  - astropy
  - bokeh
  - cython
  - gammapy
  - graphviz
  - iminuit
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib
  - numba
  - numpy
  - numpydoc
  - pandas
  - pyhessio
  - pytest
  - pytest-cov
  - psutil
  - readline
  - scikit-learn
  - scikit-image
  - scipy
  - setuptools
  - sphinx=1.6
  - sphinx_rtd_theme
  - sphinx-automodapi
  - traitlets
  - wheel
  - xz
  - yaml
  - zlib
  - iminuit
  - pytables
  - tqdm
  - pip:
      - pytest_runner
