# A conda environment with all useful package for ctapipe developers
name: cta-dev
channels:
  - default
  - cta-observatory
dependencies:
  - python=3.7
  - pip
  - astropy
  - h5py=2
  - black
  - bokeh=1
  - conda-forge::nbsphinx
  - cython
  - graphviz
  - iminuit>=1.3,<2.0.0a0
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib
  - numba
  - numpy>=1.17
  - numpydoc
  - pandas
  - pre-commit
  - psutil
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scikit-learn
  - scipy
  - setuptools
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - tqdm
  - traitlets
  - vitables
  - wheel
  - xz
  - zlib
  - zstandard
  - conda-forge::eventio>=1.5.0
  - conda-forge::corsikaio
