name: Changelog

on:
  pull_request:
    # should also be re-run when changing labels
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - 'main'

env:
  FRAGMENT_NAME_PREFIX: "docs/changes/${{ github.event.number }}"
  CATEGORIES: "feature|bugfix|api|datamodel|optimization|maintenance"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check for at least one changelog fragment
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog-needed') }}
        run: |
          changelog=$((find docs/changes -type f | grep -P "${FRAGMENT_NAME_PREFIX}\.(${CATEGORIES})\.rst") || echo "")
          if [ -z "${changelog}" ]; then
            echo "No changelog snippet found, please add a changelog entry in docs/changes, see docs/changes/README.md"
            exit 1;
          else
            echo "Found changelog snippet: $changelog"
          fi
